### ISSUE TITLE
Split strings in Tenzin Kibana dashboard

### ISSUE THREAD

**Issue by nrezvani** [threatgrid/ctia#439]
Some strings are getting split in Tenzin Kibana cita_events index such as entity.source visualized [here](http://tenzin-beta.amp.cisco.com/app/kibana#/visualize/edit/ctia_events_entity_source). Make sure you're looking at the data for the past 6 months -- the default is 15 minutes.

Here is the query:

```
`{`
  "title": "New Visualization",
  "type": "histogram",
  "params": {
    "shareYAxis": true,
    "addTooltip": true,
    "addLegend": true,
    "scale": "linear",
    "mode": "stacked",
    "times": [],
    "addTimeMarker": false,
    "defaultYExtents": false,
    "setYExtents": false,
    "yAxis": {}
  },
  "aggs": [
    {
      "id": "1",
      "type": "count",
      "schema": "metric",
      "params": {}
    },
    {
      "id": "2",
      "type": "terms",
      "schema": "segment",
      "params": {
        "field": "entity.source",
        "size": 5,
        "order": "desc",
        "orderBy": "1"
      }
    },
    {
      "id": "3",
      "type": "date_histogram",
      "schema": "group",
      "params": {
        "field": "timestamp",
        "interval": "auto",
        "customInterval": "2h",
        "min_doc_count": 1,
        "extended_bounds": {}
      }
    }
  ],
  "listeners": {}
}`
```

**Comment by nrezvani** [comment]
Here are some other fields with the same issue with ctia_events index:

entity.description
entity.reason
entity.reason_uri
entity.relations.origin
entity.relations.origin_uri
entity.short_description
entity.source
entity.source_uri
entity.title

**Comment by gbuisson** [comment]
related to #361 
related to #407 

OK, so that happened because no ES event producer slicing strategy was set on CTIA config.
However looking back at the code I found that there is an issue with the way slices index are created:

when an event is produced, we check if the target index (with the mapping) exists before writing it, but for performance reasons we memoize that check so we do it only once in a while.
The problem is that ES may automatically create an index with no mapping if we instruct it to write something to a non existing index, thus defeating the purpose of that check.

so I propose that we remove manual index check/creation and rely on index templates as needed for our next ES tasks.
