### ISSUE TITLE
Enhance CTIA store migrations

### ISSUE THREAD

**Issue by danlsgiga** [threatgrid/ctia#706]
In the last few data migrations we ran, I noticed the execution time is increasing. The latest data migration took the entire day to finish on INT using a 900 batch size, the same size used previously. And the previous one took something ~9hrs.

Here are some suggestions to improve this process and have a faster execution on the Elasticsearch end.

1. Get the current index replica count and refresh_interval values
2. Create the new indexes with 0 replicas, and set the refresh_interval to -1 (disables refresh).
3. Run the migration
4. Once finished, set the replica number and refresh_interval in the new index the same as the one from step 1.

These recommendations are also detailed [here](https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-performance.html#_other)

> When documents are replicated, the entire document is sent to the replica node and the indexing process is repeated verbatim. This means each replica will perform the analysis, indexing, and potentially merging process.
In contrast, if you index with zero replicas and then enable replicas when ingestion is finished, the recovery process is essentially a byte-for-byte network transfer. This is much more efficient than duplicating the indexing process.

Also, from a "Best practices" standpoint, bulk processing on very large objects creates a number of issues. This [thread](https://github.com/elastic/elasticsearch/issues/2237), although a bit old, but still valid, bring these issues up!

> ES does not process an HTTP request until it completes: for those working with large files, it makes quite a bit more sense to use a streaming API or otherwise run a river on the server. In an example of 2m records at about 2g uncompressed, it took longer to upload through netty than to index: indexing does not start until the http request has completed (which is reasonable).

> Yea, it represents the whole request in memory (thats how async IO works, and the fact that it needs to break the bulk request to each shard). You should make sure to break down your indexing into smaller bulk sizes.

Those 2 assumptions also creates a large issue for JVM based applications... Garbage collection! Since these objects are all being put directly into memory, and they are large, the garbage collector will probably hang ES for a couple seconds to work on those big chunks of data. Which might explain the timeout issues we are facing on the client side and the warnings we are getting in the ES logs regarding GCs.

```
[2018-05-07T20:19:01,628][INFO ][o.e.m.j.JvmGcMonitorService] [int-es-storage-search-0d26ac1fd63374489] [gc][1479179] overhead, spent [271ms] collecting in the last [1s]
[2018-05-07T20:23:36,683][INFO ][o.e.m.j.JvmGcMonitorService] [int-es-storage-search-0d26ac1fd63374489] [gc][1479454] overhead, spent [277ms] collecting in the last [1s]
```

**Comment by danlsgiga** [comment]
Another consideration that was brought up in previous conversations is to use [indexes aliases](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/indices-aliases.html) so we don't need to change application configuration and hydrant scripts to adapt to the new index name after successful data migrations.

**Comment by msprunck** [comment]
After a discussion with Craig:
- migration system needs to be updated to use aliases instead of copying
- should only copy things that need an actual data respresentation change
- don't need to copy docs to update the mapping if the mapping change is purely a policy, like strict
- don't need to copy docs if it is a new field (and not a new mapping). If no document would have that field, no need to copy
- when a change only affects certain documents in an index, update only these docs

@craigbro I think that the original motivation for creating a new index was to quickly rollback from the new to the old by changing the configuration if an error occurred during the migration. If we modify the existing indexes, this will no longer be possible.

**Comment by gbuisson** [comment]
here are some thoughts, the migration taking a full day sounds really weird considering that the last ones took maybe a couple hours, there's definately something unusual going on.

- Creating the index with 0 replicas and disabling refresh are quick wins and could be implemented quickly, however what I don't like with this approach is that data won't be available for search right away when the migration is complete, we could kick a manual refresh but I'm not sure we'll really save much time then.

- regarding @danlsgiga reference to the thread about issues with large bulks, first we're very far from indexing 2m documents at once, we usually batches of like `1000` or `2000` (configurable at will),
ES rivers are deprecated, I the issue is garbage collector related, perhaps GC times should be tweaked for production use.

- I heard previously about our issues regarding IOPS limits on Amazon, did we make sure that we didn't run in the same issue?

**Comment by danlsgiga** [comment]
Hey @gbuisson, I cheched our EBS volume credits during the migration and we were far from exhausting it.

I've mentioned the large bulk threads to relate with the Private CTIA issue we were having regarding large documents in bulk from the `investigation` index, which probably do not apply for most of the other indexes.

**Comment by gbuisson** [comment]
ok thanks @danlsgiga, I created a separate epic including all your suggestions so we can keep tracking  that efficiently

**Comment by hshahman** [comment]
No QA required.
